config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:id/braintree/new' => "braintree#new", as: "payNow"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get 'listings/new'
  get 'listings/show'
  get 'home/index'
  get 'home/partial'
  post 'home/index'
  post 'reservation/:id/braintree/checkout' => "braintree#checkout", as: "checkout"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings do
    resources :reservations
  end


  
  resources :users, controller: "users", only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/listing.rb
class Listing < ApplicationRecord
  include Filterable

  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  
  scope :bedrooms, -> (number){where('bedrooms = ?', number)}
  scope :country, -> (country){where("country like ?", "#{country}%")}

  mount_uploaders :pictures, AvatarUploader


  def self.tagged_with(name)
    Tag.find_by!(name: name).listings
  end
  
  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def show
    @reservation = Reservation.new
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    if @listing.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    @listing.destroy
    redirect_to back #method comes back from applicationController
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :address, :price_per_day, :description, :amenities, :guests, :bedrooms, :beds, :sleeping_arrangements, :baths, :country, :tag_list, {pictures: []})
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def authorize_user
    # user is redirected UNLESS they are the property owner OR a moderator/superadmin
    if current_user.id != @listing.user_id && current_user.customer?
      redirect_to root_url, notice: "You're not authorized to do that."
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h1>Edit List</h1>
<%= form_with(model: @listing, local: true) do |form| %>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title %><br/>
  </p>
  <p>
    <%= form.label :address %><br/>
    <%= form.text_field :address %><br/>
  </P>
  <p>
    <%= form.label :price_per_day %><br/>
    <%= form.text_field :price_per_day %><br/> 
  </p>
  
  <p>
    <%= form.label :description %><br/>
    <%= form.text_field :description %><br/> 
  </p>

  <p>
    <%= form.label :amenities %><br/>
    <%= form.text_field :amenities %><br/> 
  </p>
  
  <p>
    <%= form.label :guests %><br/>
    <%= form.text_field :guests %><br/> 
  </p>
  
  <p>
    <%= form.label :bedrooms %><br/>
    <%= form.text_field :bedrooms %><br/> 
  </p>

  <p>
    <%= form.label :beds %><br/>
    <%= form.text_field :beds %><br/> 
  </p>

  <p>
    <%= form.label :sleeping_arrangements %><br/>
    <%= form.text_field :sleeping_arrangements %><br/> 
  </p>
  
  <p>
    <%= form.label :baths %><br/>
    <%= form.text_field :baths %><br/> 
  </p>

  <p>
    <%= form.label :country %><br/>
    <%= form.text_field :country %><br/> 
  </p>
    <%= form.label :pictures %><br/>
    <%= form.file_field :pictures, multiple: true %><br/> 
  </p>

  <p>
    <%= form.label :tag_list, "Tags (separated by commas)" %><br />
    <%= form.text_field :tag_list %>
  </p>

  <%= form.submit %>
<% end %>

<%= link_to 'Back', home_index_path %>

app/views/listings/new.html.erb
<h1>New List</h1>

<%= form_with scope: :listing, url:listings_path , local: true do |form| %>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title %><br/>
  </p>

  <p>
    <%= form.label :address %><br/>
    <%= form.text_field :address %><br/>
  </p>

  <p>
    <%= form.label :price_per_day %><br/>
    <%= form.text_field :price_per_day %><br/>
  </p>

  <p>
    <%= form.label :description %><br/>
    <%= form.text_field :description %><br/> 
  </p>

  <p>
    <%= form.label :amenities %><br/>
    <%= form.text_field :amenities %><br/> 
  </p>
  
  <p>
    <%= form.label :guests %><br/>
    <%= form.text_field :guests %><br/> 
  </p>
  
  <p>
    <%= form.label :bedrooms %><br/>
    <%= form.text_field :bedrooms %><br/> 
  </p>

  <p>
    <%= form.label :beds %><br/>
    <%= form.text_field :beds %><br/> 
  </p>

  <p>
    <%= form.label :sleeping_arrangements %><br/>
    <%= form.text_field :sleeping_arrangements %><br/> 
  </p>
  
  <p>
    <%= form.label :baths %><br/>
    <%= form.text_field :baths %><br/> 
  </p>

  <p>
  <%= form.label :pictures %>
  <%= form.file_field :pictures, multiple: true %>
  </p>

  <p>
    <%= form.label :tag_list, "Tags (separated by commas)" %><br />
    <%= form.text_field :tag_list %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', home_index_path %>

app/views/listings/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Price Per Day:</strong>
  <%= @listing.price_per_day %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>

<p>
  <strong>Amenities:</strong>
  <%= @listing.amenities %>

<p>
  <strong>Number of Guest(s):</strong>
  <%= @listing.guests %>

<p>
  <strong>Number of Bedrooms:</strong>
  <%= @listing.bedrooms %>

<p>
  <strong>Number of Beds:</strong>
  <%= @listing.beds %>

<p>
  <strong>Sleeping Arrangements:</strong>
  <%= @listing.sleeping_arrangements %>

<p>
  <strong>Number of Baths:</strong>
  <%= @listing.baths %>
</p>


<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<%= form_with scope: @reservation , url: listing_reservations_path(@listing.id), local:true do |form| %>
  <p>
    <strong>Place a booking?</strong><br/>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %><br/>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %><br/>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', home_index_path %>