config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:id/braintree/new' => "braintree#new", as: "payNow"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get 'listings/new'
  get 'listings/show'
  get 'home/index'
  get 'home/partial'
  post 'home/index'
  post 'reservation/:id/braintree/checkout' => "braintree#checkout", as: "checkout"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings do
    resources :reservations
  end


  
  resources :users, controller: "users", only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  enum role: [ :superadmin, :moderator, :customer ]

  mount_uploader :avatar, AvatarUploader


  def name
    name = "#{first_name} " "#{last_name}"
  end
 
  def self.create_with_auth_and_hash(authentication, auth_hash)
    # byebug
    user = self.create!(
      first_name: auth_hash["info"]["first_name"],
      last_name: auth_hash["info"]["last_name"],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end
 
  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end
 end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = user_from_params

    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @listing = Listing.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params.permit!)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    avatar = user_params.delete(:avatar)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.first_name = first_name
      user.last_name = last_name
      user.avatar = avatar
    end
  end

end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.date_field :last_name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div>
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
</div>

app/views/users/edit.html.erb
<%=form_for @user do |form|%>  
  <div class="text-field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, type: 'text' %>
  </div>

  <div class="text-field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, type: 'text' %>
  </div>

  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div>
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

<%= form.submit %>

<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<img src="<%=@user.avatar.url %>" alt="..." class="img-thumbnail">

<h3>Welcome <%= "#{@user.name}" %></h3>
<%= link_to "Edit Profile", edit_user_path(@user) %>

<div>
  Contact via: <strong><%= "#{@user.email}" %></strong><br/>
</div>

<h4>List of post(s)<h4>
<% @user.listings.each do |listing| %>
  
  <% if listing.pictures? %>
    <% listing.pictures.each do |img| %>
      <img src="<%= img.url %>" alt="..." class="img-thumbnail" width="200">
    <% end %><br/>
  <% end %>
  
  <%= listing.title %>
  <%= link_to 'Destroy', listing_path(listing), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Show', listing_path(listing) %>
  <%= link_to 'Edit', edit_listing_path(listing) %><br/>
<% end %>

<h4>Reservations Made:</h4>
<% @user.reservations.each do |reservation| %>
  <strong>Start Date:</strong><br/>
  <%= reservation.start_date %><br/>
  <strong>End Date:</strong><br/>
  <%= reservation.end_date %><br/>
  <strong>Total Price: RM<%= reservation.total_price %></strong><br/>
  <%= link_to "Make Payment", payNow_path(reservation.id) %><br>
  <%= link_to 'Edit', edit_listing_reservation_path(reservation.listing, reservation), class:'btn btn-primary' %><br/>
  <%= link_to 'Destroy', listing_reservation_path(reservation.listing, reservation), method: :delete, data: { confirm: 'Are you sure?' } %><br/>

<% end %>