config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:id/braintree/new' => "braintree#new", as: "payNow"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get 'listings/new'
  get 'listings/show'
  get 'home/index'
  get 'home/partial'
  post 'home/index'
  post 'reservation/:id/braintree/checkout' => "braintree#checkout", as: "checkout"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings do
    resources :reservations
  end


  
  resources :users, controller: "users", only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    'application', 'data-turbolinks-track': 'reload' %>
  
  <title>Jamal's BnB</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Jamal's BnB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/home/index">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Logout' , sign_out_path , :method => :delete , class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Create New List', new_listing_path , class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'My Profile', user_path(current_user) , class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'Sign In' , sign_in_path , class:'nav-link' %>
          </li>
        <% end %>
      </ul>
      <%= form_with url: home_index_path, class:'form-inline my-2 my-lg-0', local: true do |form| %>
      <%= form.text_field :bedrooms , class:'form-control mr-sm-2', method: :GET , type:'search', placeholder:'Search'%>
      <%= form.submit "Search", class:'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>
    </div>
  </nav>
  
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>


  <%= yield %>
</body>
</html>